# Prepare environment

In [1]:
# Import packages
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import networkx as nx
import plotly.graph_objects as go

## Prepare dataset

In [2]:
words = "(Lehrkräftebildung OR Lehrerbildung OR Lehrkräfte OR Lehrkräftefortbildung OR Seiteneinstieg OR Quereinstieg OR Lehramt)" # The words you want tweets to include

df = pd.DataFrame()

for filename in os.listdir("data/"):
    if filename.startswith("tweets_lehrkraeftebildung_v2"):
        print(f"Found {filename}")
        df_temp = pd.read_csv(f"data/{filename}")
        #print(df_temp)
        df = pd.concat([df, df_temp])

df.drop_duplicates(inplace=True)

print(f"\nThere are {df.shape[0]} retweets in this dataset.\n")

Found tweets_lehrkraeftebildung_v2_2023-02-16_18-23-50.csv

There are 1670 retweets in this dataset.

In [6]:
print("Here arre a few examples of Tweets:\n")

display(df.text.unique()[:50])

Here arre a few examples of Tweets:

array(['RT @lueckenbildung: Viele Lehrkräfte haben iPads gestellt bekommen. Inwiefern könnten sie mit den Dienstgeräten iMessage zur kollegiumsinte…',
       'RT @SenBJF: Mit dem Ziel, die Digitalkompetenz von Lehrkräften zu stärken, haben wir eine neue #Qualifizierungsreihe gestartet. Seit letzte…',
       'RT @SiemensStiftung: 📢@HPI_DSchool und wir laden zur unsere kostenlosen #Lehrkräfte-Fortbildung „#DesignThinking in #MINT” ein. In einem Mi…',
       'RT @hav_hendrik: Die ersten Bundesländer veröffentlichen Handlungsempfehlungen für Lehrkräfte. Positiv: Es deutet sich an, dass es kein Ver…',
       'RT @AlexSchaumburg: @geierandrea2017 Da steht: Es gibt keine entsprechende VORSCHRIFT. Es hält aber auch niemand Lehrkräfte davon ab, trotz…',
       'RT @AlexHabicher: Parallel zum U15 Dialog an der @UniCologne wollen wir mit Praktiker*innen rund ums Lehramt gute Ideen entwickeln, macht m…',
       'RT @JSchmitzLeipzig: Der #Lehrkräftemangel ist dramatisch. Kinder wie Lehrkräfte stehen enorm unter Druck und sind psychisch belastet. Es i…',
       'Antwort der 🚦 : Dann kriegen die Lehrkräfte einen Bonus für die Mehrbelastung. 😂😂 https://t.co/PeiEsx5IaL',
       'RT @JMWiarda: Am Scheideweg\n\nWarum an den neuen Zahlen des Statistischen Bundesamtes zu #Lehramt und #Lehrerberuf nicht alles schlecht ist…',
       'RT @cgasch1: @focusonline Die Lage der Versorgung von Flüchtlingen ist dramatisch ❗Fehlende Wohnungen, Kitas, Lehrkräfte usw. ❗Ein Landrat…',
       "RT @tincon: Ungefragte Penisbilder: Wie geht man damit um? Darum geht's im Workshop von @IIDDeutschland – auf der TINCON @copopconvention i…",
       'Herzlichen Glückwunsch 🎉 dem ehemaligen #schulleiter der #Grundschule #Vollmaringen, der sich wie so viele #Lehrer in seinem #Beruf auch anderweitig sehr engagiert hat #Lehramt #Ehrenamt #Gesellschaft https://t.co/wjTlit5elZ',
       'RT @BildungTH: Ob Fragen zum Lehramtsstudium, dem Seiteneinstieg oder Beschäftigungsmöglichkeiten für pensionierte Lehrkräfte - wir blicken…',
       'RT @MartinGiese5: Hi Twitter-Community, für eine Interviewstudie (#Forschung) suchen wir Lehrkräfte, die gesetzlich #blind sind und über Ih…',
       'RT @mvongersdorff: Warum sollte eine Organisation, die seit Jahrzehnten gegen das Lehramt agitiert, eingeladen werden?',
       'RT @mpoessel: Wo die KMK recht hat, hat sie recht. Wenn es zu wenig Lehrkräfte gibt, dann wird es höchste Zeit, den Lehrerberuf noch belast…',
       'RT @LinksfraktionSt: Zusatzstunde für Lehrkräfte beschäftigt den Landtag - Fraktion DIE LINKE bringt Antrag ein. Es ist ein kompletter Neus…',
       'RT @schulmanagement: Wie geht Unterricht heute an der Seite von Programmen wie #ChatGPT? Und was bedeuten diese Entwicklungen für #Lehrkräf…',
       'RT @LaProf49546855: @_FrauLehrerin_ Was ist mit dem Ethos vom Installateuren, servicekräften und Bäckern? WARUM ICH SOWAS BRAUCHE HAB ICH G…',
       'RT @HoppFoundation: In dem Präsenz-Workshop „Smart City und Smart Home mit der senseBox“ am 28.3. von 10-13 Uhr gibt es noch freie Plätze.…',
       'RT @NicoleGohlke: Bereits im Jahr 2000 sind 64% der #Lehrkräfte wegen Dienstunfähigkeit vorzeitig in den Ruhestand gegangen.\nHätte in den l…',
       'RT @WayneSchlegel_: Das hätten wir sein können, aber du musstest ja Lehramt studieren. https://t.co/3Zlx2v6nS9',
       'RT @KinderJournal: 40,6 % der Lehrkräfte arbeiten in Teilzeit, jede 3. Lehrkraft ist über 50 und das Lehramtsstudium wird unbeliebter. #twl…',
       'RT @JuliaValkyrie: (wir erinnern uns: auch Lehrkräfte sind gerade in einer Tour krank 🤷) und das verbessert die Situation dann UNGEMEIN. ht…',
       'RT @JuliaValkyrie: Protokoll vom Elternabend: Fehlzeiten häufen sich. Ab sofort: Strichliste, bei zu vielen Strichen Attestpflicht. Klasse…',
       'Schluss mit unausgegorenen und unkonkreten Vorschlägen zulasten unserer Kinder und Lehrkräfte – der Ministerpräsident muss endlich Bildung zur Chefsache machen und eine "Task Force Bildung" einberufen, fordert unsere Landtagsabgeordnete @DieDannenberg https://t.co/3fSfb9y1Np',
       'Kommt da jetzt noch was? Die Recherche sollte in unter 30 sek. erledigt sein. Habe bei der Zahl der Lehrkräfte sogar noch 100 unterschlagen. \n\nhttps://t.co/x0d4dJACfA',
       'RT @denkmalstift: @PrienKarin Präsenzpflicht, egal was kommt?\nGesundheit &amp; Bildung können nicht unabhängig voneinander betrachtet werden. W…',
       'RT @rbb24: Einzelne Aktionen, um den #Lehrermangel in #Brandenburg zu kompensieren, reichen offenbar nicht mehr aus: Bildungsministerin Ern…',
       'RT @joeranDE: Eine neue JRA-Folge! Ich habe heute morgen bei @MittelbachTom angerufen und gefragt: „Agile Methoden im Unterricht – was muss…',
       'RT @schulkrise: Katarina Niewiedzial @IntMigBerlin und ihre Bezirkskolleg*innen warnen vor Konsequenzen fehlender #Schulplätze und #Lehrkrä…',
       'RT @lehrer_online: In Mecklenburg-Vorpommerns sollen ältere Lehrkräfte künftig früher als bisher weniger Unterricht für das gleiche Geld le…',
       'RT @Philo_soophie: Patient*innen: 16 Bildungsrepubliken in Deutschland\nDiagnose: #Bildungskatastrophe, zunehmendes Totalversagen\nTherapiean…',
       'RT @app_camps: Du studierst auf #Lehramt und möchtest dich gerne intensiver mit digitaler Bildung auseinandersetzen? 🎓 Unser #Stipendium bi…',
       'RT @MLUnterfinanz: Die Regierung schafft es nicht, den Lehrer:innenmangel zu bekämpfen. Deshalb sollen Lehrkräfte jetzt einfach länger arbe…',
       'Ich kann den Frust gut verstehen und auch die Kritik an viel Fachwissenschaft im LA-Studium. Lehrkräfte sind und bleiben aber Expert:innen für das Lernen und das wird man nicht durch "sich vorher mal einlesen" oder einfach mal machen, ohne zu wissen was, wie und v.a. warum. https://t.co/EILoOiQVXs',
       'RT @HSE_Heidelberg: 📢 Die #HSECluster sind bei @MeetupDE! Jetzt der Gruppe beitreten &amp; Infos zu Veranstaltungen rund um #Lehrkräftebildung,…',
       "RT @lmz_bw: Mediale Gewalt 📱👊 an Schulen und im Alltag – Was tun? Darum geht's bei unserem Fachvortrag mit Podiumsdiskussion und Get-togeth…",
       'RT @NachDenkSeiten: Lehrkräfte braucht das Land? „Es wird alles unternommen, jungen Menschen den Beruf zu verleiden.“ https://t.co/LGnBw0Ty…',
       'RT @SenBJF: Die diesjährige @PartnerSchule-Jahrestagung steht bevor! Dort wird es am 2.3. u.a. um die Ermittlung und Förderung von Berufswa…',
       'Bürokratisierung, immer mehr Verwaltungsaufwand und Leistungsdruck - kein Wunder, dass sich ambitionierte Lehrkräfte an diesem #Schulsystem die Zähne ausbeißen. Im #Podcast spricht Boris mit Philipp Schulte über die Zukunft der #Schule.  https://t.co/AwVUo5SsfR @Scrum4Schools https://t.co/fGUZ7egajG',
       'RT @birgitweber7: @KM_Bayern Wie kann man nur so realitätsverweigernd tweeten?Lehrkräfte stehen an unseren Schulen jedenfalls nicht bereit.…',
       'RT @DIMR_Berlin: Da #Polizeiproblem trendet:\n\nLehrkräfte in der polizeilichen Aus- und Fortbildung müssen rassistische und rechtsextreme Po…',
       'RT @KM_Bayern: Am Freitag erhalten rund eine Million bayerische Schüler:innen ihr #Zwischenzeugnis. 📃Bei Bedarf stehen Lehrkräfte &amp; die #St…',
       'RT @MBJSBrandenburg: Bildungsministerin Britta Ernst: „#Brandenburg ist ein attraktiver Standort für Lehrkräfte. Wir haben  viel getan, um…',
       'RT @HGrunbichler: Es müssen Lehrveranstaltungen (5 Tage bei vorhandenem \nLehramt, sonst 10 Tage) besucht werden. Werden diese unmittelbar v…',
       'RT @PartnerSchule: Im Berliner Schulportal werden jetzt mehrere Termine für eine 60-minütige Onlineschulung zum Übergang Sek I/Sek II in de…',
       'RT @Leschi3000: juchhuuuu :) ich freue mich riesig... \n\nNetzwerk stärken, OER entwickeln, Lehrkräftebildung verbessern - here we go! Es wir…',
       'Parallel zum U15 Dialog an der @UniCologne wollen wir mit Praktiker*innen rund ums Lehramt gute Ideen entwickeln, macht mit! @zflkoeln https://t.co/CgxzKujrtH',
       'RT @UWLipow: &gt; jetzt so getan wird, als wäre präpandemisch alles Gold gewesen in deutschen Schulen &amp; als wären alle dieser fortgesetzten Pr…'],
      dtype=object)

## Calculating the Importance of Users in the Network
The next step is to analyze the network. The extracted tweets and relevant information are returned as a DataFrame containing an 'edge list', or a list of all edges between nodes. The code then calculates three measures of centrality for each user in the network.

- **In-degree centrality** represents the number of edges going into a node. In the case of retweets, centrality will indicate that a user is getting a large number of retweets.
- **Out-degree centrality** represents the number of edges going out of a node. In the case of retweets, centrality will indicate that a user is retweeting a lot.
- **Betweeness centrality**  represents the number of 'shortest paths' between nodes that pass through through a specific node. In the case of tweets, it measures the extent to which a user connects other communities of users.

The code also stores the number of in_degrees (tweets) and out_degrees (retweets) to visualize later with Plotly.

In [35]:
# Create a directed network graph from the DataFrame
G = nx.from_pandas_edgelist(df, "retweeter", "tweeter", create_using=nx.DiGraph())

# Calculate the in-degree centrality for retweets
in_centrality = nx.in_degree_centrality(G)

# Caluculate the total number of tweets for later plotting purposes
in_degrees = dict(G.in_degree())

# Store centralities in DataFrame
popular_tweeters = pd.DataFrame(
    list(in_centrality.items()), columns=["username", "in-degree_centrality"]
)

# Print the most important users by their centrality
popular_tweeters.sort_values("in-degree_centrality", ascending=False).head(20)

             username  in-degree_centrality
338        Deu_Kurier              0.127495
1      lueckenbildung              0.105602
128     leseerlaubnis              0.051513
430       rosenbusch_              0.041854
16                NaN              0.034127
1221    BildungSicher              0.027688
573   SozialarbeitNRW              0.027044
1199  inesschwerdtner              0.019961
324             dm_ms              0.018030
1283  daniela_sepehri              0.017386
14    JSchmitzLeipzig              0.016742
121        derspiegel              0.012234
152     News4teachers              0.011590
278       GieslerIris              0.011590
913   BlessTheTeacher              0.010947
1214        Fuchstool              0.010303
840       MarkRackles              0.008371
63      Philo_soophie              0.008371
8         hav_hendrik              0.008371
4              SenBJF              0.007727

In [36]:
# Calculate the out-degree centrality for retweets
out_centrality = nx.out_degree_centrality(G)

# Caluculate the total number of retweets for later plotting purposes
out_degrees = dict(G.out_degree())

# Store centralities in DataFrame
active_retweeters = pd.DataFrame(
    list(out_centrality.items()), columns=["username", "out-degree_centrality"]
)

# Print the most important users by the amount they retweet
active_retweeters.sort_values("out-degree_centrality", ascending=False).head(20)

             username  out-degree_centrality
2       Bot_TwLehrerZ               0.048294
161      Mandala81966               0.003863
329       muchistaken               0.003863
94       twcampus_bot               0.003220
1499  Freihei98604242               0.003220
307          sanjosko               0.003220
636    erik_grundmann               0.003220
462   monchichiundich               0.002576
1197       Ruzzlefuzz               0.002576
285   Freihei89070736               0.002576
340   AngelikaGreine6               0.002576
653            _Wir_4               0.002576
527      SusanneJonda               0.002576
577          lothenon               0.002576
312      leerkorperin               0.001932
719     Chrisabelle09               0.001932
43      viking_kvinde               0.001932
150         sentire_x               0.001932
1169          aus_ton               0.001932
154     SvenDudkowiak               0.001932

In [32]:
# Create an undirected network graph from the DataFrame
G = nx.from_pandas_edgelist(df, "retweeter", "tweeter")

# Calculate the betweenness centrality for retweets
betweetnness = nx.betweenness_centrality(G)

# Store centralities in DataFrame
bridging_users = pd.DataFrame(
    list(betweetnness.items()), columns=["username", "betweenness"]
)

# Print the most important users by how much they bridge other users
bridging_users.sort_values("betweenness", ascending=False).head(20)

             username  betweenness
2       Bot_TwLehrerZ     0.239510
338        Deu_Kurier     0.183694
278       GieslerIris     0.180128
42      KinderJournal     0.179300
103      mrtaanderson     0.176565
1      lueckenbildung     0.164065
377      Venora_Khoon     0.122150
128     leseerlaubnis     0.112768
16                NaN     0.098759
152     News4teachers     0.064152
1221    BildungSicher     0.063673
430       rosenbusch_     0.060056
350               JNJ     0.054849
1199  inesschwerdtner     0.054795
324             dm_ms     0.053991
573   SozialarbeitNRW     0.053237
121        derspiegel     0.046212
468          Sualber1     0.046096
516    RaimundRaimund     0.034331
161      Mandala81966     0.033612

# Visualizing Follower Networks
The code below creates an interactive network visualization using Plotly. There are a number of different attributes to the plot worth noting:
- The nodes are colored by the number of retweeted tweets. Those with a number of retweeted tweets are colored blue and purple, and those who only retweet are colored yellow.
- Those with more connections in total are larger to make it easier to spot them.

In [31]:
# Create the graph and specify the layout of the graph
G = nx.from_pandas_edgelist(df, "retweeter", "tweeter")
pos = nx.drawing.layout.spring_layout(G)
nx.set_node_attributes(G, pos, "pos")

# Create a dictionary of nodes and their order
nodes_dict = {id: node for (id, node) in enumerate(G.nodes())}

# Gather edge positions for visualization
edge_x = []
edge_y = []
for edge in G.edges():
    x0_point, y0_point = G.nodes[edge[0]]["pos"]
    x1_point, y1_point = G.nodes[edge[1]]["pos"]
    edge_x.append(x0_point)
    edge_x.append(x1_point)
    edge_x.append(None)
    edge_y.append(y0_point)
    edge_y.append(y1_point)
    edge_y.append(None)

# Add edges as disconnected lines
edge_trace = go.Scatter(
    x=edge_x,
    y=edge_y,
    line=dict(width=0.5, color="#000000"),
    hoverinfo="none",
    mode="lines",
)

# Gather node positions for visualization
node_x = []
node_y = []
for node in G.nodes():
    x, y = G.nodes[node]["pos"]
    node_x.append(x)
    node_y.append(y)

# Iterate through the nodes and store the usernames and tweeting information
node_text = []
node_adjacencies = []
node_sizes = []
node_colors = []

# Iterate through the nodes and create the text to be shown on hover
for node_number, adjacencies in enumerate(G.adjacency()):
    node_text.append(  # Set the text to be shown on hover
        "Username: "
        + str(adjacencies[0])  # The username
        + "<br>"
        + "Number of Connections: "
        + str(len(adjacencies[1]))  # The number of connections
        + "<br>"
        + "Number of Retweeted Tweets: "
        + str(in_degrees[nodes_dict[node_number]])
        + "<br>"
        + "Number of Retweets: "
        + str(out_degrees[nodes_dict[node_number]])
    )
    node_adjacencies.append(len(adjacencies[1]))
    node_sizes.append(len(adjacencies[1]))
    node_colors.append(in_degrees[nodes_dict[node_number]])

# Log transform the color list for visualization purposes
node_colors = np.array(node_colors)
node_colors_temp = np.where(node_colors > 1.0e-10, node_colors, 1.0e-10)
node_colors_log = np.log10(node_colors_temp)

# Scale the size of the nodes between two values
scaler = MinMaxScaler(feature_range=(5, 30))
node_sizes = scaler.fit_transform(np.array(node_sizes).reshape(-1, 1))

# Plot the nodes
node_trace = go.Scatter(
    x=node_x,
    y=node_y,
    mode="markers",
    hoverinfo="text",
    marker=dict(
        showscale=True,
        colorscale="Plasma",  # For more colorscale options, go here: https://plotly.com/python/builtin-colorscales/
        reversescale=True,
        color=[],
        size=10,
        colorbar=dict(
            thickness=15,
            title="Number of Retweeted Tweets (Log Transformed)",
            titlefont=dict(size=12),
            xanchor="left",
            titleside="right",
            tickvals=[min(node_colors_log), max(node_colors_log)],
            ticktext=["Low", "High"],
        ),
        line=dict(color="Black", width=0.5),
    ),
)

# Set the size, color, and text of the nodes
node_trace.marker.size = node_sizes
node_trace.marker.color = node_colors_log
node_trace.text = node_text

# Customize and display the figure
fig = go.Figure(
    data=[edge_trace, node_trace],
    layout=go.Layout(
        title="<b>Retweet Network Graph for "
        + str(words)
        + "<b>",  # Set your title here
        title_x=0.5,
        titlefont_size=16,
        showlegend=False,
        paper_bgcolor="#e6e6e6",  # Set the background color (excluding the plot) here
        plot_bgcolor="#e6e6e6",  # Set the plot background color here
        font_color="#000000",
        hovermode="closest",
        margin=dict(b=20, l=5, r=5, t=40),
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        width=800,  # Adjust the width of the plot
        height=500,  # Adjust the height of the plot
    ),
)
fig.show()